### ISSUE TITLE
Gender variation for strings returns error

### ISSUE THREAD

**Issue by Boltyansky** [OpenTTD/eints#131]
I'm trying to translate "STR_NETWORK_CLIENT_LIST_PLAYER_NAME_QUERY_CAPTION" into `he_IL`.

The `en_US` base translation is "Your player name" while (for example) the `ru_RU` translation is "Ваше игровое имя". Both are gender agnostic. However, in he_IL, "player" is different depending on gender.

I tried to use as a template the pattern from "STR_NEWS_AIRCRAFT_DEST_TOO_FAR" from current `he_IL` translation file:
> "{WHITE}{VEHICLE}אינ{G 0 "ו" "ה"} יכול{G 0 "" "ה"} להגיע אל היעד הבא כי הוא מחוץ לטווח".

For "STR_NETWORK_CLIENT_LIST_PLAYER_NAME_QUERY_CAPTION" it is supposed to look like this:
> "שם השחק{G 0 "ן" "נית"} שלך".

But I get the following error message:
> "Error: String parameter 0 is out of bounds for gender queries {G ..}"

I also looked in [the docs](https://translator.openttd.org/static/docs/strings.html#gender) and tried both with and without quotation marks and got the same error.

I can spend some time and try to rephrase the string into gender neutral/agnostic form, but it may sound sort of unnatural for the casual player. So before going there, I'd be happy to get any suggestions for resolving this issue.

P.S. A possibly related issue was previously reported [here](https://github.com/OpenTTD/eints/issues/67). Perhaps there is a dependency that needs to be enabled for this string to have the option to morph according to gender?

**Comment by frosch123** [comment]
{G..} is used when talking about things inside the game, for which the gender is known. For example, in some languages individual industry types may be male or female.

The "you" in STR_NETWORK_CLIENT_LIST_PLAYER_NAME_QUERY_CAPTION on the other hand refers to the player sitting in front of the computer. OpenTTD does not ask players for their pronoun.

The only option here is to use a gender-neutral translation.

**Comment by glx22** [comment]
`0` refers to the `{VEHICLE}` in STR_NEWS_AIRCRAFT_DEST_TOO_FAR
