### ISSUE TITLE
Base language version error

### ISSUE THREAD

**Issue by pasantoro** [OpenTTD/eints#170]
When working on translating to pt_BR language I am getting repeatedly the following type of error message, after either clicking on the Save Changes & Get Next String or Get Another String buttons:
 
Error: 404 Not Found
Sorry, the requested URL 'https://translator.openttd.org/string/openttd-master/pt_BR/STR_FINANCES_YEAR_CAPTION' caused an error:
String cannot be translated, its base language version is incorrect

This behavior had begins today (2024/01/23).
Any guidance/advice?

**Comment by 2TallTyler** [comment]
I forgot to tell Web Translator about the new string control codes I added in https://github.com/OpenTTD/OpenTTD/pull/11341. We are working to fix it, so just keep checking back. Once we add support for the new codes, the page will work properly and you'll be able to translate the strings.

Sorry for the inconvenience. 🙂

**Comment by pasantoro** [comment]
Thank you for your support.

Em ter., 23 de jan. de 2024 8:32 PM, Tyler Trahan ***@***.***>
escreveu:

**Comment by frosch123** [comment]
This has been fixed today.

**Comment by pasantoro** [comment]
Thanks a lot.

Em dom., 28 de jan. de 2024 12:14 PM, frosch ***@***.***>
escreveu:
