### ISSUE TITLE
EN_AU: Unable to update 2 outdated strings

### ISSUE THREAD

**Issue by krysclarke** [OpenTTD/eints#178]
https://translator.openttd.org/translation/openttd-master/en_AU shows 2 strings are outdated:
STR_CONFIG_SETTING_DRAG_SIGNALS_FIXED_DISTANCE_HELPTEXT
STR_RAIL_TOOLBAR_TOOLTIP_BUILD_RAILROAD_SIGNALS

When I click the "Save Changes & Get Next String" button, after updating the text of either of these strings by using the "Copy Base" button, it takes me to the other string and does NOT provide a message at the top of the window saying that it has updated the string.
Yes, I have explicitly logged out and back in to the Web Translator service, and URL has `?message=...` added to it for both actions.  This is missing from the URL returned when I click the "Save Changes..." button.

**Comment by glx22** [comment]
Oh it's a revert, I guess EINTS didn't like it.

**Comment by frosch123** [comment]
This is a known bug: #133
Work around is to change the text twice: add a typo, remove it again :)

**Comment by krysclarke** [comment]
> This is a known bug: #133 Work around is to change the text twice: add a typo, remove it again :)

Yep, that worked.
