### ISSUE TITLE
Minor cosmetic issue in Languages main screen

### ISSUE THREAD

**Issue by gh658804** [OpenTTD/eints#186]
![Langs](https://github.com/OpenTTD/eints/assets/8936309/26354135-8654-401d-9ebc-308387692deb)

**Comment by frosch123** [comment]
That number is non-zero, if new string commands are added to OpenTTD without updating Eints.
It just happened earlier this year.

**Comment by gh658804** [comment]
I'm not sure i was clear enough, so i'll rephrase the question. Why in en_GB line, Invalid column is "0" while the other (Missing, Outdated, etc) are "-". Why isn't the Invalid column "-" too?

Nitpicking you may say, but as i said in the title, "Minor cosmetic". :)

**Comment by gh658804** [comment]
Ah, OK, now i get it. Thanks.
