### ISSUE TITLE
Unable to use STRING1 or anyother non standard modifiers in translations

### ISSUE THREAD

**Issue by Aswn** [OpenTTD/eints#29]
When i try to use STRING1 or STRING2 or RAW_STRING in translations from the base string, an error is shown.

Steps to replicate: (Translation to ta_IN)
STR_TIMETABLE_TRAVEL_FOR_ESTIMATED
Base lang string: Travel (for {STRING1}, not timetabled) 
Translation: பயணம் ({STRING1}, நேர அட்டவணை இடப்படாதது)

Throws the following error:
`Error: String command for position 0 is wrong, base language uses {STRING}, the translation uses {STRING1}`

I am unable to save string unless these modifiers are corrected to STRING

**Comment by glx22** [comment]
In translation you just need to replace them with {STRING}, all other kind are for master file only

**Comment by TrueBrain** [comment]
Seems the error needs to be more clear for new people :)

**Comment by Wuzzy2** [comment]
> Seems the error needs to be more clear for new people :)

I agree, I stumbled over this as well, I had to look it up in the manual to see what was going on. :-(

**Comment by Eddi-z** [comment]
my suggestion would be to just show all {STRINGn} as {STRING} to the translators.
