### ISSUE TITLE
Writing from right to left (Arabic)

### ISSUE THREAD

**Issue by AviationGamerX** [OpenTTD/eints#36]
The string editor in the translations by default types from the left to right, which messes up the Arabic sentences, which goes from the right to left, especially when English words are included, including Acronyms like "OpenTTD", or translations of multiple lines. The simplest solution so far is to type in a new line, however, the new line disappears when the translation is updated. 
If the text direction can't be changed, it would be helpful if there was a way to start new lines.

**Comment by frosch123** [comment]
I have tried adding `dir="rtl"` in various places of the html templates. Does this look more correct?

| dir=ltr | dir=rtl |
| ---- | ---- |
| ![eints_arabic_translation_ltr](https://user-images.githubusercontent.com/23150643/111875808-0105e880-899c-11eb-8a52-281d6cbd3278.png) |  ![eints_arabic_translation_rtl](https://user-images.githubusercontent.com/23150643/111875823-0a8f5080-899c-11eb-8525-8dd10ca5f20f.png) |
|  ![eints_arabic_edit_ltr](https://user-images.githubusercontent.com/23150643/111875835-12e78b80-899c-11eb-8add-7ff41087a6b4.png) |  ![eints_arabic_edit_rtl](https://user-images.githubusercontent.com/23150643/111875841-19760300-899c-11eb-80fa-caf51cef0341.png) |
|  ![eints_arabic_edit2_ltr](https://user-images.githubusercontent.com/23150643/111875844-1ed34d80-899c-11eb-9fbd-6a3b28718aac.png) |  ![eints_arabic_edit2_rtl](https://user-images.githubusercontent.com/23150643/111875849-27c41f00-899c-11eb-92b7-f552e1eb49b6.png) |

**Comment by AviationGamerX** [comment]
yes that is definitely right, is there a way I can do this or is it now implemented in the web translator?

**Comment by frosch123** [comment]
I'll add it to the web translator. I am just unable to check the result myself, so I asked first :)

**Comment by AviationGamerX** [comment]
alright thank you so much :)

**Comment by LordAro** [comment]
Don't close the issue before it's been fixed!

**Comment by frosch123** [comment]
The fix has been deployed. Have fun!

**Comment by AviationGamerX** [comment]
> The fix has been deployed. Have fun!

thank you so much :)
