### ISSUE TITLE
"String editing Manual" link is dead

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/eints#49]
The string editing page has a link to the "String editing Manual" pointing to a openttdcoop.org URL, which is dead.

https://github.com/OpenTTD/eints/blob/28ada7e7c9bb82bc129392992c28f9d766b11865/views/string_form.tpl#L6

This should perhaps be pointed to a wiki.openttd.org page instead?

**Comment by glx22** [comment]
I think it should be possible to generate and include docs in the docker itself, removing any external access.
