### ISSUE TITLE
Eints is reverting/ignoring translations, but they still exist in the History

### ISSUE THREAD

**Issue by absay** [OpenTTD/eints#70]
I've noticed Eints is overwriting or, more accurately, "reverting" translations, but the updated changes are still shown in the History. This is what is happening:

1. I change a translation of a string.
2. Eints saves the translation correctly. When I refresh and review the **strings page**, everything looks in order.
3. However, at some point, when I download the latest build and open the game, I discover many of the changes were ignored/reverted to an older translation.
4. Then, I go back to the strings page  and it now shows these "reversions", as if I had done nothing.
5. However, if I click on a string I suspect Eints reverted, and try to see the history, it shows the saved change, though the current translated string is still the older version.
6. If I change the string again, the next build of the game apparently registers the updates alright.

Here's an image that explains it better: ![image](https://user-images.githubusercontent.com/3838371/167519648-4bd377d7-aedb-4dc3-b163-71b55feb7415.png)

As you can see, the changes were successfully saved 2 weeks ago, but the current translated string  is showing the previous, wrong version. Whenever I change any translation, I make sure I get the blue message telling me the string was successfully changed, so I don't know what's happening or if this occurs to other translators.

Is there a way to prevent this behavior, or better yet, **to recover all those updates** as the new translations, since they are apparently correctly stored somewhere, in order to avoid going over each string again?

edit:

Something really funky is happening here. If I _fix_ any translation, the History now says the "older" version is the one made 2 weeks ago...

![image](https://user-images.githubusercontent.com/3838371/167521702-e6f02a73-8f88-440c-8bfe-ae23d9254e22.png)

This is quickly becoming a mess lol. 😵

**Comment by glx22** [comment]
Due to an unnoticed disabling of the eints-to-git workflow (the one pushing translations updates once a day), there was no update of translation in game between Apr 23, 2022 and May 1, 2022, but all the changes made during this period should have been applied on May 1, 2022.

**Comment by absay** [comment]
Yes, the changes are not making it to the commits on the OpenTTD master, that's part of the issue, this is why the builds come out without these updates, and the wrong strings still appear in the game.

And I was suspecting the git workflpw outage could have been implicated. But it apparently is not it since: 1) there are a lot of unapplied changes still, despite the reactivation of the git workflow, and 2) the same issue continues to happen with recent changes I've made, "recent" as in a couple of days ago.

I don't have an screenshot to show, but if you [see this commit](https://github.com/OpenTTD/OpenTTD/commit/9c58ea7a37ee7e9bbf7d561165a6c8d384e6b82f#diff-07d72f4c038b99567cb3c469a3e15a6cfdb9af33b41d681d7420fbe7592b0d14), I was mostly changing `vehículo de carretera` to `autotransporte` (and its plural form). The intention was an entire replacement of that word. Again, I made **REALLY sure** I didn't miss any string. The strings page showed nothing when Ctrl+F "vehículo de carretera". But then, the build was released the next day, I downloaded it, played the game and found missing updated strings again (in the Finance window), so I had to go back to the strings page, and when I Ctrl+F "vehiculo de carretera" once more, I got results! So, I had to amend them, [changes that can be seen in the commit of the next day](https://github.com/OpenTTD/OpenTTD/commit/867f6a5964379a6974d3960edd92a249056a6fa5#diff-07d72f4c038b99567cb3c469a3e15a6cfdb9af33b41d681d7420fbe7592b0d14). Only then the updates stuck.

How come I make changes, I get the blue notification, I check that the changes are correct in the list of strings, I trust everything goes OK, even the history saves such changes (made 2 weeks ago, not 10 months ago), but in the next build many changes are reverted? There's something definitely happening here, and I apologize if I sound repetitive, but it's frustrating to have hours of work lost to an unknown bug (or an action on my part? But what?), and the idea of going over those changes again 😅.

**Comment by frosch123** [comment]
Do you have another example?
If/when you have another example, please do not fix it.

I can only check what is going on, as long as the text is still wrong. After you fixed it, I have no idea what could have been wrong.

**Comment by absay** [comment]
Thanks for the help frosch! Here are more examples that remain unfixed:

* `STR_ORDERS_LIST_TOOLTIP`
* `STR_ORDER_REFIT_TOOLTIP`
* `STR_TIMETABLE_TOOLTIP`
* `STR_TOOLTIP_SORT_CRITERIA`
* `STR_DEPOT_CLONE_AIRCRAFT_INFO_HANGAR_WINDOW` - this one's a mess, nothing is consistent here!

> Also, not everyone may know this: The text shown in the screenshot as "es_ES" is indeed the current es_ES translation, not the es_MX translation. Eints shows translations from similar languages for guidance.

Not sure about that... it apparently is the other way around. Every single "es_ES" translation that shows up in that particular part of the page is actually es_MX, not es_ES.

For example:

* `STR_ORDERS_LIST_TOOLTIP`
  * Enits shows as "similar" es_ES translation: _{BLACK}Lista de órdenes. Clic para resaltar. Ctrl+Clic para ir al destino de la orden_
  * Actual es_ES translation in the lang file has: _{BLACK}Lista de órdenes - Clica en una orden para resaltarla. Ctrl+clic para desplazarse a la estación de la orden_
* `STR_NETWORK_CLIENT_LIST_ASK_CLIENT_BAN`
  * Enits shows as "similar" es_ES translation: _{YELLOW}¿Bloquear acceso al jugador "{STRING}"?_
  * Actual es_ES translation in the lang file : _{YELLOW}¿Estás seguro de que deseas prohibir el acceso al jugador '{STRING}'?_

I can recognize that all those es_ES translations that are show for guidance are _my_ translations for es_MX, so I guess that's a new issue here? Eints it's not grabbing the text from the appropriate similar language, at least not across Spanish lang files.

Thanks again for the patience. Hopefully this help you guys see what could be happening.

**Comment by frosch123** [comment]
Ok, the "similar languages" thingie is obviously broken :) I found the issue, and will fix that.

About the lost translations: There is some weirdness on the staging version as well. Apparently all translations changed "2 months ago", which correlates with the last dependency update. I am testing some things there.

**Comment by frosch123** [comment]
@absay I'll restore the correct translations via script. You do not have to do anything. But I may only get to it tomorrow evening.

**Comment by absay** [comment]
Thanks a lot for the work. I see you even added timestamps to the history in Eints. 😄

**Comment by frosch123** [comment]
Restored the translations:
https://github.com/OpenTTD/OpenTTD/commit/1eed52f294879313142b392771560cdbdd37a0fd

Have fun translating, and please report bugs again :)
